### ISSUE TITLE
spaからの派生 一人（温泉？）旅について議論する

### ISSUE THREAD

**Issue by mizutani** [mizutani/spa#2]
### why
一人旅の情報は集まりずらい、みんなで知見を共有したい

### 議題
- リポジトリ名
- 一人旅（温泉）の定義

**Comment by mizutani** [comment]
現在出ている リポジトリ名の案
- ぼっち旅

**Comment by mokdd** [comment]
http://www.bettei-kai.jp/room.html

サイトはイケてないですが、知人の話によると良さそうな香りがする宿です（今度行ってきます）

**Comment by mizutani** [comment]
メモ：

温泉でいいのかどうかも議論ポイント。
体験がすばらいい風呂であれば温泉じゃなくてもいいのでは？

**Comment by mokdd** [comment]
https://morinoyu.co.jp/

露天じゃなくても内風呂が温泉 & お値段も良心的です（姉が行って良かったらしいです）

**Comment by tomoya-osada** [comment]
近所に良さげな浴場があってもいいすよね。
今治一人で言ったとき近所にこれがあったので普通のホテル取りました。（そして奇跡的にその日だけ臨時休業でした）
https://kisuke.com/yu-imabari/

**Comment by mizutani** [comment]
一人旅の定義
- 温泉である必要は無い、ただし、すらばしい風呂の体験ができること
- spa を主目的にするのなら、このリポジトリで問題なし

**Comment by mizutani** [comment]
@tomoya-osada  @mokdd リポジトリ名 Botchi Travel ですかね？

**Comment by mokdd** [comment]
ぼっちの綴りってBotchiなんですねw
温泉にこだわらなければそれで良い気がします 🙆

**Comment by tomoya-osada** [comment]
![image](https://user-images.githubusercontent.com/16718080/59673605-845d3d80-91fc-11e9-9c73-0419236825b8.png)

**Comment by mizutani** [comment]
議論の場所はこちらに移しましょう。https://github.com/mizutani/botchi-travel

**Comment by mizutani** [comment]
https://github.com/mizutani/botchi-travel/issues/1
